import image from "../src/assets/Products/image.png";
import image1 from "../src/assets/Products/image2.png";
import {
  image2,
  image3,
  image4,
  image5,
} from "../src/assets/SingleProduct/index";

const productData = [
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [image1, image3, image4, image5, image2, image3, image4, image4],
    category: "Retrofit Switches",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [
      image1,
      image3,
      image4,
      image5,
      image2,
      image3,
      image4,
      image4,
      image4,
    ],
    category: "Retrofit Switches",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [
      image1,
      image3,
      image4,
      image5,
      ,
      image4,
      image2,
      image3,
      image4,
    ],
    category: "Retrofit Switches",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [image1, image3, image4, image5, image2, image3, image4],
    category: "Retrofit Switches",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [image, image3, image4, , image4, image5, image2, image3, image4],
    category: "Retrofit Switches",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [
      image,
      image3,
      image4,
      image5,
      image4,
      image4,
      image2,
      image3,
      image4,
    ],
    category: "Retrofit Switches",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [image, image3, image4, image5, image2, image3, image4, image4],
    category: "Retrofit Switches",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [image, image3, image4, image5, image2, image3, image4],
    category: "Retrofit Switches",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [image, image3, image4, image5, image2, image3, image4],
    category: "Retrofit Switches",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [image1, image3, image4, image5, image2, image3, image4],
    category: "Retrofit Switches",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [image1, image3, image4, image5, image2, image3, image4],
    category: "Smart Sensors",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [image1, image3, image4, image5, image2, image3, image4],
    category: "Smart Sensors",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [image1, image3, image4, image5, image2, image3, image4],
    category: "Smart Sensors",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [image1, image3, image4, image5, image2, image3, image4],
    category: "Smart Sensors",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [image, image3, image4, image5, image2, image3, image4],
    category: "Smart Sensors",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [image, image3, image4, image5, image2, image3, image4],
    category: "Smart Sensors",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [image, image3, image4, image5, image2, image3, image4],
    category: "Smart Sensors",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [image, image3, image4, image5, image2, image3, image4],
    category: "Smart Sensors",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [image, image3, image4, image5, image2, image3, image4],
    category: "Smart Sensors",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [image1, image3, image4, image5, image2, image3, image4],
    category: "Smart Sensors",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [image, image3, image4, image5, image2, image3, image4],
    category: "Smart Sensors",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [image, image3, image4, image5, image2, image3, image4],
    category: "Smart Sensors",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [image1, image3, image4, image5, image2, image3, image4],
    category: "Smart Sensors",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [image1, image3, image4, image5, image2, image3, image4],
    category: "Smart Sensors",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [image1, image3, image4, image5, image2, image3, image4],
    category: "Smart Curtain",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [image1, image3, image4, image5, image2, image3, image4],
    category: "Smart Curtain",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [image1, image3, image4, image5, image2, image3, image4],
    category: "Smart Curtain",
  },
  {
    name: "4 Switch Control With Remote & 1 FAN (10 amp each)",
    originalPrice: "₹5,490.00",
    discountedPrice: "₹5,215.50",
    imageSrc: [image1, image3, image4, image5, image2, image3, image4],
    category: "Smart Curtain",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [image, image3, image4, image5, image2, image3, image4],
    category: "Smart Curtain",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [image, image3, image4, image5, image2, image3, image4],
    category: "Smart Curtain",
  },
  {
    name: "Another Product Name",
    originalPrice: "₹4,990.00",
    discountedPrice: "₹4,699.00",
    imageSrc: [image, image3, image4, image5, image2, image3, image4],
    category: "Smart Curtain",
  },

  // Add more products here
];

export default productData;
